### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by christ776** [elliottminns/blackfish-example#3]
Hi, 

I'm just trying to compile this example in OS X, but I'm getting this error:

Packages/Libuv-0.1.0/module.modulemap:3:12: error: header '/usr/local/include/uv.h' not found
    header "/usr/local/include/uv.h"

Is there a missing dependency ?

**Comment by christ776** [comment]
Sorry, I didn't know I had to install libuv with brew!

**Comment by elliottminns** [comment]
No problem! Sorry I didn't get to comment on this before hand.
