### ISSUE TITLE
"error while loading shared libraries" on launch

### ISSUE THREAD

**Issue by floschliep** [elliottminns/blackfish-example#4]
Hi,

I cloned the repo on a Linux server (15.10) and ran `swift build -Xlinker -L/usr/local/lib` to build the executable. When trying to launch the executable using `.build/debug/BlackfishApp`, I get the following error: 

```
.build/debug/BlackfishApp: error while loading shared libraries: libuv.so.1: cannot open shared object file: No such file or directory
```

I installed libuv before cloning the repo and it's also in my /usr/local/lib folder. After building the executable I also got this warning:

```
/usr/bin/ld: warning: cannot find entry symbol ad_strip; defaulting to 0000000000404c70
```

Did I miss something?

**Comment by elliottminns** [comment]
I have a feeling it's to do with shared libs not being supported on swift. Can you do an `ls` on `/usr/local/lib` and see if you have the .a or .la versions available?

**Comment by floschliep** [comment]
There's a `libuv.a`, `libuv.la`, `libuv.so`, `libuv.so.1` and `libuv.so.1.0.0`.

**Comment by elliottminns** [comment]
Could you remove the `.so`'s and then do a clean build of your project to see if that resolves it? I haven't got my VM up and running to test at the moment. It may have to be a temporary work around for the mean time until libuv can be embedded in the project.

**Comment by floschliep** [comment]
That's it, thanks!

Compiling a debug build works without any warnings and I can launch it. When compiling a release build I get the same warning mentioned above `cannot find entry symbol ad_strip` and the executable crashes on launch:

```
BlackfishApp: src/unix/process.c:269: uv__write_int: Assertion `n == sizeof(val)' failed.
Aborted
```

**Comment by elliottminns** [comment]
Hmm, I'll try and figure out what's causing this. I've not tested with 15.10 however so it may be an issue there. If I get time today I'll try and see if there's a work around
